//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Users = new HashSet<User>();
        }
    
        public string Country1 { get; set; }
        public int ID_Country { get; set; }
        public string PhotoCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\CountryPhotos\{PhotoCountry}";
            }
        }
    }
}
