//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Currency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Currency()
        {
            this.Wallets = new HashSet<Wallet>();
        }
    
        public int PriceInRub { get; set; }
        public string Currency1 { get; set; }
        public int ID_Currency { get; set; }
        public string CurrencyPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }

        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\CurrencyPhotos\{CurrencyPhoto}";
            }
        }

    }
}
