//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int ID_Wallet { get; set; }
        public int Balance { get; set; }
        public int ID_Currency { get; set; }
        public int ID_User { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}
